// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwludjixlagdfgkcfgxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bHVkaml4bGFnZGZna2NmZ3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTIzMjMsImV4cCI6MjA1OTE2ODMyM30.rGe4272_IFbpxt8CiDZqk6buD_3D2ERB1TNld45m6kA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);