// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuyoqentnajwhhericoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eW9xZW50bmFqd2hoZXJpY29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODcwNDksImV4cCI6MjA1OTE2MzA0OX0.QTXl9gc5-RbzxnFpcqveVVL4tigq6qSSq8130sYUD0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);